import { MOVEMENT_PATTERN_IDS, type MovementPatternId } from '../movementPatterns/movementPatterns'
import type { MediaAsset, MediaManifestEntry, MediaProvenance } from './mediaSchema'

/**
 * THE production-media manifest: which asset a given exercise shows, and where
 * that asset came from.
 *
 * NEVER IMPORT THIS MODULE STATICALLY FROM A BOOT-PATH FILE. It is data, it grows
 * with the catalog, and the first-paint budget has no room for it. Reach it the
 * same way the exercise catalog is reached:
 *
 *     const { mediaRecordFor } = await import('../../catalog/media/mediaManifest')
 *
 * It is deliberately absent from `./index.ts` so that importing the media SCHEMA
 * — which several boot-path modules legitimately do — cannot drag the manifest in
 * behind it. `mediaManifest.test.ts` walks `src/` and fails if any non-test module
 * imports this one statically.
 *
 * WHAT PHASE 2 ACTUALLY SHIPS, STATED PLAINLY: zero real demonstrations. Every
 * exercise in the catalog currently resolves to a generated placeholder poster —
 * an abstract force diagram for its movement pattern, not a demonstration of the
 * exercise. That is a deliberate, documented gap, not an oversight, and closing
 * it is a decision the project owner has to make before final acceptance. See
 * `docs/media-license-register.md`. Every placeholder record carries
 * `isPlaceholder: true`, so "how big is the gap" is one query, and the Phase 8
 * acceptance test is a one-line change from the reporting test that exists today.
 *
 * THE MANIFEST DOES NOT ENUMERATE EXERCISES. A hard-coded row per exercise would
 * be a second copy of the catalog's id list, drifting the first time an id is
 * added. Instead `PRODUCTION_MEDIA` lists only the exercises that have real,
 * licensed assets, and everything else resolves to its movement pattern's
 * placeholder. Adding an exercise therefore cannot leave it with no media, and
 * cannot leave it silently counted as finished.
 */

/* ------------------------------------------------------------- placeholders */

/** The date the committed placeholder posters were generated. */
export const PLACEHOLDER_GENERATED_ON = '2026-09-02'

/** Where `scripts/make-exercise-posters.mjs` writes, relative to the public root. */
export const PLACEHOLDER_POSTER_DIR = 'media/posters'

export const PLACEHOLDER_POSTER_WIDTH = 480
export const PLACEHOLDER_POSTER_HEIGHT = 270
export const PLACEHOLDER_POSTER_MIME = 'image/png' as const

/**
 * The provenance of a generated poster. Honest by construction: we drew it, from
 * coordinates in a script in this repository, so the source is checkable, the
 * author is us, and redistribution is ours to permit.
 */
export const PLACEHOLDER_PROVENANCE: MediaProvenance = {
  source: 'generated by scripts/make-exercise-posters.mjs',
  author: 'Workout Conductor',
  licence: 'original work, project-owned',
  licenceUrl: null,
  redistributionPermitted: true,
  verifiedOn: PLACEHOLDER_GENERATED_ON,
  verifiedBy: 'Phase 2 media review',
  notes:
    'Original abstract diagram drawn from coordinates authored in the generator: a force ' +
    'arrow against a body axis and a ground reference. Nothing is traced, scraped, or ' +
    'photographed, and no human figure is drawn, because this is NOT a demonstration of ' +
    'the exercise and must not be presented as one. Shared by every exercise in the ' +
    'movement pattern; the UI draws the exercise name over it.',
}

/**
 * The byte size of each committed poster, transcribed from the generator's
 * output. It is transcribed rather than computed so the manifest stays plain,
 * reviewable data — and `mediaManifest.test.ts` compares every number against the
 * file on disk, so a stale transcription fails CI instead of shipping a manifest
 * that misreports what it ships.
 */
export const PLACEHOLDER_POSTER_BYTES: Readonly<Record<MovementPatternId, number>> = {
  'horizontal-push': 3700,
  'horizontal-pull': 4146,
  'vertical-push': 3639,
  'vertical-pull': 3704,
  squat: 3807,
  hinge: 5072,
  lunge: 4199,
  'hip-extension': 3817,
  carry: 5007,
  'calf-raise': 2991,
  'knee-flexion': 4396,
  'knee-extension': 5338,
  'hip-abduction': 3100,
  'hip-adduction': 3138,
  'isolation-curl': 4538,
  'isolation-extension': 4446,
  'isolation-raise': 5554,
  'isolation-fly': 4896,
  shrug: 4691,
  rotation: 5152,
  'anti-extension': 3391,
  'anti-rotation': 4720,
  'anti-lateral-flexion': 5692,
}

/** Path of the shared placeholder poster for a movement pattern, under the public root. */
export function placeholderPosterPath(patternId: MovementPatternId): string {
  return `${PLACEHOLDER_POSTER_DIR}/${patternId}.png`
}

/** Every placeholder poster path, in canonical pattern order. */
export const PLACEHOLDER_POSTER_PATHS: readonly string[] = MOVEMENT_PATTERN_IDS.map(placeholderPosterPath)

/** The poster asset for a movement pattern. */
export function placeholderPoster(patternId: MovementPatternId): MediaAsset {
  return {
    path: placeholderPosterPath(patternId),
    kind: 'poster',
    mimeType: PLACEHOLDER_POSTER_MIME,
    width: PLACEHOLDER_POSTER_WIDTH,
    height: PLACEHOLDER_POSTER_HEIGHT,
    byteSize: PLACEHOLDER_POSTER_BYTES[patternId],
    durationMs: null,
    provenance: PLACEHOLDER_PROVENANCE,
  }
}

/* ------------------------------------------------------------------ records */

/**
 * What an exercise has to tell the manifest about itself. A structural subset of
 * `Exercise`, restated here so that this module never imports the catalog data or
 * its schema — and so a caller can ask about an exercise it has only partly
 * loaded.
 */
export interface MediaExerciseRef {
  readonly id: string
  readonly movementPattern: MovementPatternId
  readonly productionEnabled: boolean
}

/**
 * A manifest entry plus the one fact the schema cannot carry: whether this is a
 * finished asset or a stand-in.
 *
 * `isPlaceholder` is a separate field on a wrapper rather than a field inside
 * `MediaManifestEntry` because the entry is a `z.strictObject` owned by the media
 * schema, and because "is this finished" is a project-status fact, not part of the
 * media contract. What matters is that it is impossible to hold a record without
 * also holding the answer — a placeholder can never be mistaken for a finished
 * asset by a caller that simply forgot to check a flag it never saw.
 */
export interface MediaManifestRecord {
  readonly entry: MediaManifestEntry
  readonly isPlaceholder: boolean
  /** The pattern whose shared poster is standing in; `null` for a real asset. */
  readonly placeholderPattern: MovementPatternId | null
}

/**
 * Real, licensed, exercise-specific media. EMPTY AT PHASE 2 — every row added
 * here needs a row in `docs/media-license-register.md` first, and the test suite
 * enforces the pairing in both directions.
 */
export const PRODUCTION_MEDIA: readonly MediaManifestRecord[] = []

const PRODUCTION_BY_EXERCISE_ID = new Map<string, MediaManifestRecord>(
  PRODUCTION_MEDIA.map((record) => [record.entry.exerciseId, record]),
)

/** The stand-in record for an exercise: its pattern's poster, no demonstration. */
export function placeholderRecordFor(ref: MediaExerciseRef): MediaManifestRecord {
  return {
    entry: {
      exerciseId: ref.id,
      poster: placeholderPoster(ref.movementPattern),
      demonstrations: [],
    },
    isPlaceholder: true,
    placeholderPattern: ref.movementPattern,
  }
}

/**
 * THE lookup. Real media when we have it, the movement pattern's placeholder
 * otherwise — so this never returns null and no screen has to render an empty
 * frame. What it will not do is pretend: the record says which it gave you.
 */
export function mediaRecordFor(ref: MediaExerciseRef): MediaManifestRecord {
  return PRODUCTION_BY_EXERCISE_ID.get(ref.id) ?? placeholderRecordFor(ref)
}

/** True when an exercise has a real, exercise-specific moving demonstration. */
export function hasRealDemonstration(record: MediaManifestRecord): boolean {
  return !record.isPlaceholder && record.entry.demonstrations.length > 0
}

/** The manifest for a set of exercises, in the order they were given. */
export function buildMediaManifest(refs: readonly MediaExerciseRef[]): MediaManifestRecord[] {
  return refs.map(mediaRecordFor)
}

/** The schema-shaped entries, for validation or for anything that wants the contract only. */
export function mediaManifestEntries(records: readonly MediaManifestRecord[]): MediaManifestEntry[] {
  return records.map((record) => record.entry)
}

/* ---------------------------------------------------------------- reporting */

/**
 * How much of the catalog actually has media, counted rather than estimated.
 *
 * Phase 8's acceptance gate reads this: `withPlaceholder` must be 0 for
 * production-enabled exercises. Until then the same numbers are reported so the
 * gap is visible every time the suite runs.
 */
export interface MediaCoverage {
  /** Every exercise asked about. */
  readonly total: number
  /** Those the product actually offers. Non-production exercises are exempt. */
  readonly productionEnabled: number
  /** Production-enabled exercises with a real, exercise-specific demonstration. */
  readonly withRealDemonstration: number
  /** Production-enabled exercises with a real poster but no moving demonstration. */
  readonly withRealPosterOnly: number
  /** Production-enabled exercises still showing a generated placeholder. */
  readonly withPlaceholder: number
  /** Which ones, in catalog order, so a report can name them. */
  readonly placeholderExerciseIds: readonly string[]
}

export function summariseMediaCoverage(refs: readonly MediaExerciseRef[]): MediaCoverage {
  const live = refs.filter((ref) => ref.productionEnabled)
  const placeholderExerciseIds: string[] = []
  let withRealDemonstration = 0
  let withRealPosterOnly = 0

  for (const ref of live) {
    const record = mediaRecordFor(ref)
    if (record.isPlaceholder) {
      placeholderExerciseIds.push(ref.id)
    } else if (hasRealDemonstration(record)) {
      withRealDemonstration += 1
    } else {
      withRealPosterOnly += 1
    }
  }

  return {
    total: refs.length,
    productionEnabled: live.length,
    withRealDemonstration,
    withRealPosterOnly,
    withPlaceholder: placeholderExerciseIds.length,
    placeholderExerciseIds,
  }
}

/** A one-line summary for a report, a console line, or a test failure message. */
export function describeMediaCoverage(coverage: MediaCoverage): string {
  return (
    `${coverage.withRealDemonstration}/${coverage.productionEnabled} production-enabled exercises ` +
    `have a real demonstration; ${coverage.withRealPosterOnly} have a real poster only; ` +
    `${coverage.withPlaceholder} still show a generated placeholder.`
  )
}
