import type { Exercise } from '../../catalog/exercises/exerciseSchema'
import type { MuscleGroupId, MuscleId } from '../../catalog/muscles/muscles'

/**
 * THE VOCABULARY OF VOLUME. What a set is worth, what a group has had, and how
 * recently it had it.
 *
 * WHY THESE TYPES ARE STRUCTURAL RATHER THAN `Exercise`-SHAPED. Volume counting
 * needs exactly three fields off an exercise — its id and its two muscle lists —
 * and demanding a whole `Exercise` would mean a caller holding a history row had
 * to go and find the catalog entry before it could add up last week. `Phase 7`
 * will hold rows, not catalog entries, so the narrow type is the one that will
 * survive contact with it.
 *
 * NOTHING HERE READS A CLOCK. `daysAgo` is a number the caller works out from its
 * own clock, exactly as the conflict engine's `RecentTraining` does. An engine
 * that called `Date.now()` would count a Sunday-night session into two different
 * weeks depending on when you asked.
 *
 * HISTORY IS EMPTY TODAY, AND THAT IS THE COMMON CASE. Every function in this
 * folder has to produce a sensible answer from nothing, because until Phase 7
 * ships there is nothing. `VolumeLedger.hasHistory` is how "trained zero sets" is
 * kept distinguishable from "we have no idea", which are the same number and
 * completely different facts: the first is a deficit worth acting on, the second
 * is an absence that must not be read as one.
 */

/** The minimum an exercise has to state for its volume to be counted. */
export type VolumeExercise = Pick<Exercise, 'id' | 'primaryMuscles' | 'secondaryMuscles'>

/** One exercise's working sets, from a session that happened or one being built. */
export interface WorkedExercise {
  readonly exercise: VolumeExercise
  /**
   * Effective working sets. Warm-up sets are NOT counted; use `creditSets` to
   * turn a list of set kinds into this number.
   */
  readonly sets: number
}

/**
 * One session's worth of work.
 *
 * `items` and `setsByGroup` are both accepted and both count, because the two
 * things that will feed this differ in what they kept. A session generated by
 * Phase 3 knows its exercises; a `RecentWorkoutSummary` from Phase 7 may only
 * have kept per-group totals. A summary-only session contributes GROUP volume
 * and no per-muscle detail — which is honest, rather than inventing heads it
 * never recorded.
 */
export interface SessionVolume {
  /** Whole days since the session. 0 is today. Worked out by the caller. */
  readonly daysAgo: number
  readonly items?: readonly WorkedExercise[]
  readonly setsByGroup?: Readonly<Partial<Record<MuscleGroupId, number>>>
}

/** What one muscle head got. Heads are counted separately; they are separate. */
export interface MuscleVolume {
  readonly muscle: MuscleId
  readonly group: MuscleGroupId
  /** Sets where this head was named a PRIMARY muscle. Full credit. */
  readonly directSets: number
  /** Sets where it was named a SECONDARY muscle. Raw, before the discount. */
  readonly indirectSets: number
  /** `directSets + SECONDARY_MUSCLE_CREDIT * indirectSets`. */
  readonly effectiveSets: number
}

/**
 * What one group got.
 *
 * A SET COUNTS ONCE PER GROUP, however many of the group's heads it names. A
 * dumbbell press naming both `upper-chest` and `mid-chest` is one set of chest
 * work, not two; summing the head credits to get the group total would inflate
 * every multi-head exercise and make the chest of a person who benches look
 * twice as trained as it is.
 */
export interface GroupVolume {
  readonly group: MuscleGroupId
  /** Sets where the group was reached through a primary muscle. */
  readonly directSets: number
  /** Sets where it was reached ONLY through a secondary muscle. Raw. */
  readonly indirectSets: number
  /** `directSets + SECONDARY_MUSCLE_CREDIT * indirectSets`. */
  readonly effectiveSets: number
  /** How many distinct exercises reached the group at all. */
  readonly exercises: number
}

/** Everything counted, indexed both ways. Immutable; the same input builds it identically. */
export interface VolumeLedger {
  /** Every muscle that got anything, in canonical muscle order. */
  readonly byMuscle: readonly MuscleVolume[]
  /** Every group that got anything, in canonical group order. */
  readonly byGroup: readonly GroupVolume[]
  /** Total effective sets across every group. */
  readonly totalSets: number
  /** How many sessions were inside the window and were counted. */
  readonly sessions: number
  /**
   * False when nothing was counted at all. See the file note: zero sets and no
   * history are the same number and different facts.
   */
  readonly hasHistory: boolean
  /** Effective sets for a group. 0 for a group that got nothing. */
  groupSets(group: MuscleGroupId): number
  /** Effective sets for one head. 0 for a head that got nothing. */
  muscleSets(muscle: MuscleId): number
  /** The whole row for a group, or `null`. */
  forGroup(group: MuscleGroupId): GroupVolume | null
}
